# Generated by Django 5.2.5 on 2025-08-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('iso2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_full', models.CharField(max_length=160)),
                ('title_short', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('theme', models.CharField(choices=[('forest', 'Forest'), ('mountain', 'Mountain'), ('sea', 'Sea'), ('desert', 'Desert'), ('city', 'City')], default='forest', max_length=16)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('altitude_m', models.PositiveIntegerField(default=0)),
                ('cities_count', models.PositiveSmallIntegerField(default=1)),
                ('capacity', models.PositiveSmallIntegerField(default=20)),
                ('booked', models.PositiveSmallIntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hero_image', models.ImageField(upload_to='trips/hero/')),
                ('about_md', models.TextField(blank=True)),
                ('important_md', models.TextField(blank=True)),
                ('payment_md', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travelapp.country')),
            ],
        ),
    ]
