# Generated by Django 5.2.5 on 2025-08-19 10:42

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import travelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-date_start', 'title_full'), 'verbose_name': 'Путешествие', 'verbose_name_plural': 'Путешествия'},
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(help_text='Например: UZ, RU, KZ. Будет автоматически приведён к верхнему регистру.', max_length=2, verbose_name='ISO‑код (2 буквы)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Официальное название страны (на русском или английском)', max_length=80, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='about_md',
            field=models.TextField(blank=True, verbose_name='О туре (Markdown)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='altitude_m',
            field=models.PositiveIntegerField(default=0, help_text='Максимальная высота маршрута в метрах', verbose_name='Высота (м)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='booked',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Забронировано мест'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Мест всего'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cities_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Сколько городов посещаем', verbose_name='Городов'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='travelapp.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hero_image',
            field=models.ImageField(upload_to=travelapp.models.trip_hero_upload_to, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='important_md',
            field=models.TextField(blank=True, verbose_name='Важно знать (Markdown)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публиковать'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payment_md',
            field=models.TextField(blank=True, verbose_name='Оплата (Markdown)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Итоговая цена за участника', max_digits=10, verbose_name='Цена (USD)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автогенерация из короткого названия при сохранении', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='theme',
            field=models.CharField(choices=[('forest', 'Лес'), ('mountain', 'Горы'), ('sea', 'Море'), ('desert', 'Пустыня'), ('city', 'Город')], default='forest', max_length=16, verbose_name='Тема оформления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title_full',
            field=models.CharField(help_text='Показывается на карточке и странице тура', max_length=160, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title_short',
            field=models.CharField(help_text='Для слага и компактных мест', max_length=80, verbose_name='Короткое название'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(django.db.models.functions.text.Lower('iso2'), name='idx_country_iso2_ci'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['slug'], name='idx_trip_slug'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['country', 'date_start'], name='idx_trip_country_date'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_published'], name='idx_trip_published'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('iso2'), name='uniq_country_iso2_ci'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='chk_trip_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('booked__lte', models.F('capacity'))), name='chk_trip_booked_lte_capacity'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('price_usd__gte', 0)), name='chk_trip_price_nonneg'),
        ),
    ]
