# Generated by Django 5.2.5 on 2025-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_country_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(help_text='Например: UZ, RU, KZ. При сохранении будет приведён к верхнему регистру.', max_length=2, verbose_name='ISO‑код (2 буквы)'),
        ),
    ]
