# Generated by Django 5.2.5 on 2025-08-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_profile_registrationrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='country',
            name='uniq_country_iso2_ci',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='idx_country_iso2_ci',
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(help_text='Например: UZ, RU, KZ. При сохранении будет приведён к верхнему регистру.', max_length=2, unique=True, verbose_name='ISO-код (2 буквы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='E-mail подтверждён'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso2'], name='idx_country_iso2'),
        ),
    ]
