# Generated by Django 5.2.5 on 2025-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcode',
            options={'ordering': ('-created_at',), 'verbose_name': 'Email code', 'verbose_name_plural': 'Email codes'},
        ),
        migrations.AddIndex(
            model_name='emailcode',
            index=models.Index(fields=['email', 'purpose', 'used'], name='accounts_em_email_a0e6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcode',
            index=models.Index(fields=['created_at'], name='accounts_em_created_d1ee35_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailcode',
            constraint=models.UniqueConstraint(fields=('email', 'code', 'purpose', 'used'), name='uniq_active_email_code_per_purpose'),
        ),
    ]
